
#ifndef AUDIO_BUFFERS
#define AUDIO_BUFFERS

// Base class for all audio buffers (one kind only ?)...
// So needed ? Why not a simple float buffer[512] ?
class AudioBuffer
{
};

// Based on prey-predator model, see :
// https://en.wikipedia.org/wiki/Lotka%E2%80%93Volterra_equations
// Here the "preys" are the audio buffers generated by the case modules.
// The "predator" is the audio device (the sample rate follows the CD default)

// Like a lot of place in this program, I should "guard" some "variables" against the thread monster...
class AudioQueue
{
};

#endif // AUDIO_BUFFERS
